### ISSUE TITLE
Revisión proyecto final

### ISSUE THREAD

**Issue by JaviAPS94** [damian9668/backend#1]
- Falta indentar correctamente todo el código
- Unused imports, hay imports que no se estan usando por ende deberían ser borrados
- Hay un router de test que seguramente lo hiciste para probar pero debería ser borrado ya para la entrega:

const { testRouter } = require("./src/routes/test");

- Eliminar los console.logs de todo el proyecto, esta bien usarlos para pruebas pero hay que eliminarlos ya para subir la última versión.
- Eliminar código comentado que no tiene ninguna utilidad

//app.get('/', routes.getRoot);
//ContenedorMongoDb.connect();
//serverMode(modo,port);

**Comment by damian9668** [comment]
hola alex, decidi realizar el proyecto desde cero, en estos dias voy a estar subiendo la re entrega
